#Лабораторная работа №2

##Численное решение систем линейных алгебраических уравнений

In [2]:
from math import *
import numpy as np
import time as t
import matplotlib.pyplot as plt

Метод Гаусса с выбором главного элемента

In [3]:
n = 4
A = np.array([[1.85, 0.70, -0.12, -0.18],
              [0.16, 0.19, 0.79, 0.11],
              [1.13, 2.77, 0.18, -0.20],
              [1.14, 1.01, 0.55, 3.22]])
b = np.array([-0.49,1.27,5.675,6.765])

In [4]:
num_eliminated_x = 0
num_equation = num_eliminated_x + 1
num_compared_current_a = num_eliminated_x + 1
num_max_a = num_eliminated_x
while True:
  while True:
    if abs(A[num_compared_current_a][num_eliminated_x]) > abs(A[num_max_a][num_eliminated_x]):
      num_max_a = num_compared_current_a
    if num_compared_current_a < n - 1:
      num_compared_current_a = num_compared_current_a + 1
    else:
      break
  while True:
    if num_max_a == num_eliminated_x:
      break
    column = num_eliminated_x
    while True:
      A[num_eliminated_x][column] = A[num_equation][column]
      if column < n-1:
        column = column + 1
      else:
        b[num_eliminated_x] = b[num_equation]
        break
  while True:
    factor = A[num_equation][num_eliminated_x]/A[num_eliminated_x][num_eliminated_x]
    A[num_equation][num_eliminated_x] = 0
    column = num_eliminated_x + 1
    while True:
      A[num_equation][column] = A[num_equation][column] - factor*A[num_eliminated_x][column]
      if column < n - 1:
        column = column + 1
      else:
        break
    b[num_equation] = b[num_equation] - factor*b[num_eliminated_x]
    if num_equation < n - 1:
      num_equation = num_equation + 1
    else:
      break
  if num_eliminated_x < n - 2:
    num_eliminated_x = num_eliminated_x + 1
  else:
    break

KeyboardInterrupt: 

In [ ]:
x = np.array([0, 0, 0, 0])

In [ ]:
print(A)

[[ 1.85        0.7        -0.12       -0.18      ]
 [ 0.          2.34243243  0.2532973  -0.09005405]
 [ 0.          0.          0.56137418  3.35316488]
 [ 0.          0.          0.          0.        ]]


In [18]:
def gauss_elimination_pivot(A, b):
  n = len(b)

  for i in range(n):
    max_index = i
    max_val = abs(A[i, i])

    for j in range(i+1, n):
      if abs(A[j, i]) > max_val:
        max_index = j
        max_val = abs(A[j, i])

    A[[i, max_index]] = A[[max_index, i]]
    b[i], b[max_index] = b[max_index], b[i]

    for j in range(i+1, n):
      factor = A[j, i] / A[i, i]
      b[j] -= factor * b[i]
      A[j, i:] = A[j, i:] - factor * A[i, i:]

  print('Преобразованная верхнетреугольная матрица:')
  print(A)
  print(b)

  x = np.zeros(n)
  for i in range(n-1, -1, -1):
    x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

  return x

In [19]:
A = np.array([[1.85, 0.70, -0.12, -0.18],
              [0.16, 0.19, 0.79, 0.11],
              [1.13, 2.77, 0.18, -0.20],
              [1.14, 1.01, 0.55, 3.22]])
b = np.array([-0.49,1.27,5.675,6.765])

In [24]:
x = gauss_elimination_pivot(A, b)
print("Решение:", x)

Преобразованная верхнетреугольная матрица:
[[ 1.85        0.7        -0.12       -0.18      ]
 [ 0.          2.34243243  0.2532973  -0.09005405]
 [ 0.          0.          0.78637937  0.13054459]
 [ 0.          0.          0.          3.25997275]]
[-0.49        5.9742973   0.98219626  4.88995913]
Решение: [-1.   2.5  1.   1.5]


In [32]:
r = x.dot(A)
print(r)

[-1.85        5.15608108  1.53962261  4.97536859]


In [27]:
print(r - b)

[-1.36       -0.81821622  0.55742635  0.08540946]


In [29]:
x_changed = gauss_elimination_pivot(A, r-b)
print("Решение: ", x_changed)

Преобразованная верхнетреугольная матрица:
[[ 1.85        0.7        -0.12       -0.18      ]
 [ 0.          2.34243243  0.2532973  -0.09005405]
 [ 0.          0.          0.78637937  0.13054459]
 [ 0.          0.          0.          3.25997275]]
[-1.36       -0.81821622  0.55742635  0.08540946]
Решение:  [-0.52627616 -0.4244756   0.7045024   0.02619944]


In [31]:
print(b - r)

[ 1.36        0.81821622 -0.55742635 -0.08540946]


Метод Зейделя

In [35]:
def seidel(A, b, x0, tol=1e-8, max_iter=1000):
    n = len(A)
    x = x0[:]
    for k in range(max_iter):
        x_new = x[:]
        for i in range(n):
            sum1 = sum(A[i][j] * x_new[j] for j in range(i))
            sum2 = sum(A[i][j] * x[j] for j in range(i+1, n))
            x[i] = (b[i] - sum1 - sum2) / A[i][i]
        if all(abs(x[i] - x_new[i]) < tol for i in range(n)):
            return x
    raise ValueError("Seidel method did not converge")

x0 = [0, 0, 0, 0]

x = seidel(A, b, x0)
print("Solution:", x)

Solution: [1.8571428544819355, 1.4285714235156775, 0.8571428544819355, 0]
