#Лабораторная работа №2

##Численное решение систем линейных алгебраических уравнений

In [47]:
from math import *
import numpy as np
import time as t
import matplotlib.pyplot as plt

Метод Гаусса с выбором главного элемента

In [48]:
n = 4
A = np.array([[1.85, 0.70, -0.12, -0.18],
              [0.16, 0.19, 0.79, 0.11],
              [1.13, 2.77, 0.18, -0.20],
              [1.14, 1.01, 0.55, 3.22]])
b = np.array([-0.49,1.27,5.675,6.765])

In [58]:
num_eliminated_x = 0
num_equation = num_eliminated_x + 1
num_compared_current_a = num_eliminated_x + 1
num_max_a = num_eliminated_x
while True:
  while True:
    if abs(A[num_compared_current_a][num_eliminated_x]) > abs(A[num_max_a][num_eliminated_x]):
      num_max_a = num_compared_current_a
    if num_compared_current_a < n - 1:
      num_compared_current_a = num_compared_current_a + 1
    else:
      break
  while True:
    if num_max_a == num_eliminated_x:
      break
    column = num_eliminated_x
    while True:
      A[num_eliminated_x][column] = A[num_equation][column]
      if column < n-1:
        column = column + 1
      else:
        b[num_eliminated_x] = b[num_equation]
        break
  while True:
    factor = A[num_equation][num_eliminated_x]/A[num_eliminated_x][num_eliminated_x]
    A[num_equation][num_eliminated_x] = 0
    column = num_eliminated_x + 1
    while True:
      A[num_equation][column] = A[num_equation][column] - factor*A[num_eliminated_x][column]
      if column < n - 1:
        column = column + 1
      else:
        break
    b[num_equation] = b[num_equation] - factor*b[num_eliminated_x]
    if num_equation < n - 1:
      num_equation = num_equation + 1
    else:
      break
  if num_eliminated_x < n - 2:
    num_eliminated_x = num_eliminated_x + 1
  else:
    break

KeyboardInterrupt: 

In [54]:
x = np.array([0, 0, 0, 0])

In [55]:
print(A)

[[ 1.85        0.7        -0.12       -0.18      ]
 [ 0.          2.34243243  0.2532973  -0.09005405]
 [ 0.          0.          0.56137418  3.35316488]
 [ 0.          0.          0.          0.        ]]


In [ ]:
def gauss_elimination_pivot(A, b):
  n = len(b)

  for i in range(n):
    max_index = i
    max_val = abs(A[i, i])

    for j in range(i+1, n):
      if abs(A[j, i]) > max_val:
        max_index = j
        max_val = abs(A[j, i])

    A[[i, max_index]] = A[[max_index, i]]
    b[i], b[max_index] = b[max_index], b[i]

    for j in range(i+1, n):
      factor = A[j, i] / A[i, i]
      b[j] -= factor * b[i]
      A[j, i:] = A[j, i:] - factor * A[i, i:]

  x = np.zeros(n)
  for i in range(n-1, -1, -1):
    x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

  print(A)
  print(b)

  return x

A = np.array([[1.85, 0.70, -0.12, -0.18],[0.16, 0.19, 0.79, 0.11],[1.13, 2.77, 0.18, -0.20],[1.14, 1.01, 0.55, 3.22]])
b = np.array([-0.49,1.27,5.675,6.765])

x = gauss_elimination_pivot(A, b)
print("Solution:", x)

[[ 1.85        0.7        -0.12       -0.18      ]
 [ 0.          2.34243243  0.2532973  -0.09005405]
 [ 0.          0.          0.78637937  0.13054459]
 [ 0.          0.          0.          3.25997275]]
[-0.49        5.9742973   0.98219626  4.88995913]
Solution: [-1.   2.5  1.   1.5]


Метод Зейделя

In [ ]:
def seidel(A, b, x0, tol=1e-6, max_iter=1000):
  n = len(b)
  x = x0.copy()

  for k in range(max_iter):
    x_new = np.zeros(n)
    for i in range(n):
      x_new[i] = (b[i] - np.dot(A[i, :], x_new) + A[i, i]*x[i]) / A[i, i]

    if np.linalg.norm(x_new - x) < tol:
      return x_new

    x = x_new

A = np.array([[1.85, 0.70, -0.12, -0.18],[0.16, 0.19, 0.79, 0.11],[1.13, 2.77, 0.18, -0.20],[1.14, 1.01, 0.55, 3.22]])
b = np.array([-0.49,1.27,5.675,6.765])
x0 = np.zeros(4)

x = seidel(A, b, x0)
print("Solution:", x)

Solution: None
